### PR TITLE
Add a default masthead image

### PR DESCRIPTION
**Pull request by rdeago**
This PR adds a default masthead image, shown in all pages (including home and archives) unless they have their own.

### CODE REVIEW

**Comment by atiq-cs** [comment]
Thanks for all the PRs in this repo. I will merge them into this repo after your PRs merged into CleanBlog repo i.e., statiqdev/CleanBlog#23

**Comment by rdeago** [comment]
> Thanks for all the PRs in this repo. I will merge them into this repo after your PRs merged into CleanBlog repo i.e., [statiqdev/CleanBlog#23](https://github.com/statiqdev/CleanBlog/pull/23)

You're welcome. Of course all the PR's, at least most of them, were meant to be merged after the CleanBlog PR; I tested them by replacing the theme locally, don't know if there was a better way but it was quick and got the job done.

**Comment by atiq-cs** [comment]
I have converted the html to markdown for `ImageAttribution` line.

**Comment by rdeago** [comment]
> I have converted the html to markdown for `ImageAttribution` line.

I understand the rationale and totally agree in principle: HTML knowledge is not required to write a post, so why should one have to deal with tags just for image attribution?

Unfortunately, Markdown just won't work here, unless the theme's Razor code is changed to somehow call the Markdown renderer instead of injecting `ImageAttribution` as raw HTML.

I'm afraid I'm at a loss here - tagging @daveaglick in the hope he may help.

---

As a side note, most stock photography sites have copypaste-ready attribution HTML. See for example:

- [Unsplash](https://unsplash.com/photos/urnV5XxCuA4) (click on "Download free"; find attribution code 
-  in the pop-up, with a nice Copy button)
- [Pexels](https://www.pexels.com/photo/brown-concrete-building-on-top-of-mountain-14558772) (same as Unsplash)
- [Freepik](https://www.freepik.com/free-photo/house-isolated-field_10025444.htm) (click on "Download", then on "Free download"; find attribution code, and the Copy button, right in the middle of the image)
 
Even when that is not available, as is your case with DALL-E2 for example, the most complicated HTML one would have to write is one or two `<a>` tags. So yes, the principle still stands, but enforcing it here might be less than paramount.

**Comment by rdeago** [comment]
I just asked about this [in the Statiq.Web repo](https://github.com/statiqdev/CleanBlog/issues/27). We're probably better off discussing it there, rather than on a closed PR in a repo that uses a repo that is based on Statiq.Web. 😄

**Pull request merged**
